name       : virglrenderer
version    : 0.10.3
release    : 13
source     :
    - https://gitlab.freedesktop.org/virgl/virglrenderer/-/archive/virglrenderer-0.10.3/virglrenderer-virglrenderer-0.10.3.tar.bz2 : b8a1f13e128033083713519e4c936bc9df0afe76109f1f2bd5e077b8c13a2d44
license    : MIT
component  : virt
summary    : Allows KVM guests to render OpenGL 3D calls on the host GPU via mesa
description: |
    Virgil is a research project to investigate the possibility of creating a virtual 3D GPU for use inside qemu virtual machines, that allows the guest operating system to use the capabilities of the host GPU to accelerate 3D rendering. The plan is to have a guest GPU that is fully independent of the host GPU.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libva)
    - pkgconfig(x11)
    - libpth-devel
setup      : |
    %meson_configure -Dvideo=true
build      : |
    %ninja_build
install    : |
    %ninja_install
