name        : virglrenderer
version     : 0.5.0
release     : 0
source      :
    - https://www.freedesktop.org/software/virgl/virglrenderer-0.5.0.tar.gz : f55059083bafee603e9ae0a177d5a36dc75fa4a2b3662cc6f547d1bc068d24cf
license     : MIT
component   : virt
summary     : Allows KVM guests to render OpenGL 3D calls on the host GPU via mesa
description : |
    Virgil is a research project to investigate the possibility of creating a
    virtual 3D GPU for use inside qemu virtual machines, that allows the guest
    operating system to use the capabilities of the host GPU to accelerate 3D
    rendering. The plan is to have a guest GPU that is fully independent of the
    host GPU.
builddeps   :
    - pkgconfig(libdrm)
    - pkgconfig(epoxy)
    - pkgconfig(gl)
setup       : |
    %configure
build       : |
    %make
install     : |
    %make_install

