name       : virglrenderer
version    : 0.7.0
release    : 4
source     :
    - https://www.freedesktop.org/software/virgl/virglrenderer-0.7.0.tar.gz : 36ccf8c304544a529f2535e48c098dde2b048f582f67bfba11867e34c6ee9853
license    : MIT
component  : virt
summary    : Allows KVM guests to render OpenGL 3D calls on the host GPU via mesa
description: |
    Virgil is a research project to investigate the possibility of creating a
    virtual 3D GPU for use inside qemu virtual machines, that allows the guest
    operating system to use the capabilities of the host GPU to accelerate 3D
    rendering. The plan is to have a guest GPU that is fully independent of the
    host GPU.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gl)
    - pkgconfig(libdrm)
    - libpth-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
