name       : virglrenderer
version    : 0.10.1
release    : 12
source     :
    - https://gitlab.freedesktop.org/virgl/virglrenderer/-/archive/virglrenderer-0.10.1/virglrenderer-virglrenderer-0.10.1.tar.bz2 : c9d56f5fcd14cf6d1423b7d953f387fd856d6601534ec4ff548c9a8dd0f86083
license    : MIT
component  : virt
summary    : Allows KVM guests to render OpenGL 3D calls on the host GPU via mesa
description: |
    Virgil is a research project to investigate the possibility of creating a virtual 3D GPU for use inside qemu virtual machines, that allows the guest operating system to use the capabilities of the host GPU to accelerate 3D rendering. The plan is to have a guest GPU that is fully independent of the host GPU.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libva)
    - pkgconfig(x11)
    - libpth-devel
setup      : |
    %meson_configure -Dvideo=true
build      : |
    %ninja_build
install    : |
    %ninja_install
